services:

  mysql:
    image: mysql:8.0
    container_name: pipeline-mysql

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pipeline_dashboard

    ports:
      - "3307:3306"

    volumes:
      - mysql-data:/var/lib/mysql

  backend:

    build:
      context: ./backend

    container_name: pipeline-backend

    depends_on:
      - mysql

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/pipeline_dashboard
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

    ports:
      - "8080:8080"

  frontend:

    build:
      context: ./frontend

    container_name: pipeline-frontend

    depends_on:
      - backend

    ports:
      - "80:80"

volumes:
  mysql-data:
